INSERT INTO
    cat_prospectos(
        idu_promotor,
        nom_nombre,
        nom_apellido_paterno,
        nom_apellido_materno,
        num_telefono,
        num_rfc
    )
VALUES (
        1,
        'JUAN',
        'MEZA',
        'ANTUNA',
        '667895424',
        '14521785412'
    ), (
        2,
        'JORGE',
        'ESPARZA',
        'ENRIQUEZ',
        '6674859658',
        '142598567854'
    ), (
        3,
        'LUIS',
        'GUZMAN',
        'ENRIQUEZ',
        '6677986285',
        '13452345AS'
    );