INSERT INTO
    cat_prospectos(
        idu_promotor,
        nom_nombre,
        nom_apellido_paterno,
        nom_apellido_materno,
        num_telefono,
        num_rfc
    )
VALUES (
        1,
        'Juan',
        'Meza',
        'Antuna',
        '667895424',
        '14521785412'
    ), (
        2,
        'Jorge',
        'Esparza',
        'Enqriquez',
        '6674859658',
        '142598567854'
    );